spring.application.name=Judiciary-Management-System
spring.datasource.url=jdbc:mysql://mysql-3f4887d8-judiciaryproject.i.aivencloud.com:16005/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

jwt.secret=MySuperSecretKeyForJudiciaryProject123456789
jwt.expiration=86400000
logging.level.org.springframework.security=DEBUG

file.upload-dir=uploads