spring.application.name=Judiciary-Management-System
spring.datasource.url=jdbc:mysql://localhost:3306/judiciary_db
spring.datasource.username=root
spring.datasource.password=Siddhant@1811

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.formate_sql=true

jwt.secret=MySuperSecretKeyForJudiciaryProject123456789
jwt.expiration=86400000
logging.level.org.springframework.security=DEBUG

file.upload-dir=uploads